export const siteConfig = {
  author: 'Martín Ferreira',
  description:
    'Este es un blog personal, el cual ire volcando mi experiencia a los retos enfrentados en este proceso de aprendizaje del desarrollo web, el mismo esta creado con Next.js 14, typescript, tailwindcss, shadcn, velite',
  keywords: [
    'blog',
    'personal',
    'martin ferreira',
    'martin',
    'ferreira',
    'desarrollo web',
    'next js',
    'next',
    'react js',
    'react',
    'javascript',
    'js',
    'typescript',
    'ts',
    'frontend',
    'backend',
    'fullstack',
    'full-stack',
    'node',
    'nodejs',
    'express',
    'mongo',
    'mongodb',
    'postgresql',
    'postgres',
    'postgre',
    'tailwindcss',
    'tailwind',
    'shadcn',
    'shadcn-ui',
    'shadcn-ui-react',
    'velite',
  ],
  links: {
    linkedin: 'https://www.linkedin.com/in/martin-ferreira-yic/',
    github: 'https://github.com/martinfyic',
    personalSite: 'https://www.martin-ferreira.com/',
  },
  name: 'CodeZen',
  url: 'https://example.com',
};

export type SiteConfig = typeof siteConfig;
